In [4]:
import numpy as np

# Creating Arrays in Numpy

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [6]:
print(arr)

[1 2 3 4 5 6 7 8 9]


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
marks = []
for i in range(1,21):
    k = int(input("Enter your marks: "))
    marks.append(k)

marks_arr = np.array(marks)
print(marks_arr)

Enter your marks:  65
Enter your marks:  12
Enter your marks:  12
Enter your marks:  18
Enter your marks:  98
Enter your marks:  176
Enter your marks:  187
Enter your marks:  143
Enter your marks:  12
Enter your marks:  90
Enter your marks:  87
Enter your marks:  34
Enter your marks:  986
Enter your marks:  123
Enter your marks:  986
Enter your marks:  235
Enter your marks:  235
Enter your marks:  298
Enter your marks:  276
Enter your marks:  209


[ 65  12  12  18  98 176 187 143  12  90  87  34 986 123 986 235 235 298
 276 209]


In [10]:
print(marks_arr.ndim)

1


In [11]:
arr2 = np.array([[1,2,3,4,5],[1,2,3,6,10]])
print(arr2)
print(arr2.ndim)

[[ 1  2  3  4  5]
 [ 1  2  3  6 10]]
2


In [12]:
arr3 = np.array([
    [
        [98,17,15,87,12,19,109,165],
        [45,98,90,87,67,65,56,90]],
    [
        [123,90,87,89,198,176,190,123],
        [23,90,54,23,198,187,123,98]]
])

In [13]:
print(arr3)
print(arr3.ndim)

[[[ 98  17  15  87  12  19 109 165]
  [ 45  98  90  87  67  65  56  90]]

 [[123  90  87  89 198 176 190 123]
  [ 23  90  54  23 198 187 123  98]]]
3


In [14]:
arr4 = np.array((1,2,4,6,9))
print(arr4)
print(type(arr4))

[1 2 4 6 9]
<class 'numpy.ndarray'>


In [26]:
mat1 = np.array(((3,5,76,21,90),
                (3,5,1,98,32),
                (56,98,87,90,12),
                (34,98,98,87,100)))
print(mat1)
print(mat1.ndim)

[[  3   5  76  21  90]
 [  3   5   1  98  32]
 [ 56  98  87  90  12]
 [ 34  98  98  87 100]]
2


In [16]:
print(mat1[0][0])

3


In [17]:
d = np.array(37)
print(d)
d.ndim

37


0

In [18]:
print(marks_arr)

[ 65  12  12  18  98 176 187 143  12  90  87  34 986 123 986 235 235 298
 276 209]


# Indexing Array elements

In [19]:
print(marks[0])

65


In [20]:
print(marks[1])

12


In [21]:
for i in range(20):
    print(marks_arr[i])

65
12
12
18
98
176
187
143
12
90
87
34
986
123
986
235
235
298
276
209


In [22]:
print(arr2)

[[ 1  2  3  4  5]
 [ 1  2  3  6 10]]


In [24]:
for i in range(5):
    for j in range(2):
        print(arr2[j][i])
    print()

1
1

2
2

3
3

4
6

5
10



In [31]:
for i in range(5):
    for j in range(4):
        print(mat1[j][i])
    print()


3
3
56
34

5
5
98
98

76
1
87
98

21
98
90
87

90
32
12
100

