# Data types in numpy

- int8 - For 8 bit signed integers
- int16 - For 16 bit signed integers
- int32 - For 32 bit signed integers
- int64 - For 64 bit signed integers

For unsigned integer the data type used in numpy is `uint8`, `uint16`, `uint32` and `uint64` respectively. This also follows the same way for `float` data type used for half precision,single precision and double precision floating point values

In [48]:
import numpy as np

## Checking the datatype of a numpy array with `np.dtype` attribute

### int32 data type in numpy

In [49]:
arr = np.array([1,2,3,4,12,17,18,19,45,32,89,198,432])
print("Data type",arr.dtype)

Data type int32


In [50]:
arr = np.array([1.4,1.6,8.56,9.87,10.87,56.74])
print("Data type",arr.dtype)

Data type float64


### <U1 Datatype for single character strings
The data type for single character strings in `<U1` in numpy.However **note that this data type changes accordingly as you store few words as strings and when values of different datatypes are stored then also this data type changes accordingly.**

In [51]:
arr = np.array(["A","S","D","F","G"])
print("Data type",arr.dtype)

Data type <U1


In [52]:
arr = np.array(["A","S","D","F","G",1,6,5,3,6])
print(arr)
print("Data type",arr.dtype)

['A' 'S' 'D' 'F' 'G' '1' '6' '5' '3' '6']
Data type <U11


In [53]:
arr = np.array(["A","S","D","F","G",1.98,1.76,45.87,32.98])
print(arr)
print("Data type",arr.dtype)

['A' 'S' 'D' 'F' 'G' '1.98' '1.76' '45.87' '32.98']
Data type <U32


In [54]:
arr1 = np.array([3,1,87,76,87,98,90,90,89],dtype=np.int8)
print("Data type: ",arr1.dtype)
print(arr1)

Data type:  int8
[ 3  1 87 76 87 98 90 90 89]


In [55]:
arr2 = np.array([3,1,87,76,87,98,90,90,89],dtype="f")
print("Data type: ",arr2.dtype)
print(arr2)

Data type:  float32
[ 3.  1. 87. 76. 87. 98. 90. 90. 89.]


In [56]:
arr3 = np.array([65,87,98,98,21,87,109,187,165,154,132])
print(arr3)
print("Data type of arr3 was",arr3.dtype)
float_arr = np.float16(arr3)
print(float_arr)
print("Data type of the arr3 after type casting is",float_arr.dtype)
arr3_def = np.int_(float_arr)
print(arr3_def)
print("Data type of arr3 after type casting to the default integer type is",arr3_def.dtype)

[ 65  87  98  98  21  87 109 187 165 154 132]
Data type of arr3 was int32
[ 65.  87.  98.  98.  21.  87. 109. 187. 165. 154. 132.]
Data type of the arr3 after type casting is float16
[ 65  87  98  98  21  87 109 187 165 154 132]
Data type of arr3 after type casting to the default integer type is int32


In [57]:
marks = np.array([44.6,87.98,89.98,23.76,143.7641,9976.1256,3467.98126523,2198.94532187])
print(marks)
print("Data type of the marks array is",marks.dtype)
marks_float32 = np.float32(marks)
print(marks_float32)
print("Data type of the marks array after conversion is",marks_float32.dtype)

[  44.6          87.98         89.98         23.76        143.7641
 9976.1256     3467.98126523 2198.94532187]
Data type of the marks array is float64
[  44.6      87.98     89.98     23.76    143.7641 9976.126  3467.9812
 2198.9453]
Data type of the marks array after conversion is float32


In [58]:
fruits = np.array(["Apple","Orange","Guava","Pineapple","Watermelon","Muskmelon"])
print(fruits)
print("Data type: ",fruits.dtype)

['Apple' 'Orange' 'Guava' 'Pineapple' 'Watermelon' 'Muskmelon']
Data type:  <U10


In [59]:
fruits_price = np.array(["Apple","Orange","Guava","Pineapple","Watermelon","Muskmelon",34,981,908,765,541])
print(fruits_price)
print("Data type: ",fruits_price.dtype)

['Apple' 'Orange' 'Guava' 'Pineapple' 'Watermelon' 'Muskmelon' '34' '981'
 '908' '765' '541']
Data type:  <U11


In [60]:
mat1 = np.array([[34,54,67,12,98,100,176,154,143,122,121],
                 [23,321,345,121,454,189,176,143,121,347,1098],
                 [387,231,987,143,190,165,187,166,155,144,2376],
                 [154,432,276,287,276,124,549,870,987,213,987]],dtype=np.int16)
print(mat1)
print("Data type of the 2D array is",mat1.dtype)

[[  34   54   67   12   98  100  176  154  143  122  121]
 [  23  321  345  121  454  189  176  143  121  347 1098]
 [ 387  231  987  143  190  165  187  166  155  144 2376]
 [ 154  432  276  287  276  124  549  870  987  213  987]]
Data type of the 2D array is int16


In [65]:
mat2 = np.array([[34,54,67,12,98,100,176,154,143,122,121],
                 [23,321,345,121,454,189,176,143,121,347,1098],
                 [387,231,987,143,190,165,187,166,155,144,2376],
                 [154,432,276,287,276,124,549,870,987,213,987]],dtype=np.float16)
print(mat2)
print("Data type of the 2D array is",mat2.dtype)
mat2_default_val = np.int_(mat2)
print()
print(mat2_default_val)
print("Data of the 2D array now is",mat2_default_val.dtype)

[[  34.   54.   67.   12.   98.  100.  176.  154.  143.  122.  121.]
 [  23.  321.  345.  121.  454.  189.  176.  143.  121.  347. 1098.]
 [ 387.  231.  987.  143.  190.  165.  187.  166.  155.  144. 2376.]
 [ 154.  432.  276.  287.  276.  124.  549.  870.  987.  213.  987.]]
Data type of the 2D array is float16

[[  34   54   67   12   98  100  176  154  143  122  121]
 [  23  321  345  121  454  189  176  143  121  347 1098]
 [ 387  231  987  143  190  165  187  166  155  144 2376]
 [ 154  432  276  287  276  124  549  870  987  213  987]]
Data of the 2D array now is int32


# The `np.astype()` function in numpy

In [70]:
arr4 = np.array([565,125,901,980,876,124,678,656,232,245,1674])
print(arr4)
print("Data type:",arr4.dtype)
float_arr4 = arr4.astype(np.float32)
print(float_arr4)
print("Data type:",float_arr4.dtype)

[ 565  125  901  980  876  124  678  656  232  245 1674]
Data type: int32
[ 565.  125.  901.  980.  876.  124.  678.  656.  232.  245. 1674.]
Data type: float32
