# Random Module in numpy

## `rand()` function
The `numpy.random.rand()` function is used to generate random values between 0 and 1

In [1]:
import numpy as np

In [2]:
values = np.random.rand(4)
print(values)

[0.47061086 0.31690738 0.46476376 0.85187317]


In [3]:
var1 = np.random.rand(5,5,3)
print(var1)

[[[0.56940469 0.7551318  0.9907337 ]
  [0.71919486 0.80202266 0.6030765 ]
  [0.65793374 0.97427853 0.84738578]
  [0.6759435  0.51993162 0.73844175]
  [0.33578689 0.63585716 0.18681816]]

 [[0.64179852 0.47769708 0.48247182]
  [0.08550461 0.94908753 0.2594544 ]
  [0.35813342 0.81309328 0.19872837]
  [0.59143275 0.6173841  0.07245924]
  [0.03411024 0.72742237 0.5342368 ]]

 [[0.12137964 0.57621458 0.80482846]
  [0.11112779 0.04538653 0.24256495]
  [0.93395597 0.90689772 0.25082031]
  [0.61701154 0.50824007 0.14036307]
  [0.29779256 0.2268859  0.66462549]]

 [[0.21606134 0.19324511 0.57042065]
  [0.69783146 0.09318918 0.8303507 ]
  [0.37693865 0.06187384 0.57208442]
  [0.85284452 0.48993677 0.70501014]
  [0.6404548  0.24992332 0.53473031]]

 [[0.78985755 0.58684436 0.62182864]
  [0.15817811 0.13470507 0.45381137]
  [0.04266698 0.54391671 0.14414997]
  [0.49199355 0.365497   0.04025566]
  [0.08370775 0.26576876 0.17342014]]]


## `randn()` function
The `numpy.random.randn()` function is used to generate random values **close to zero** and it may include **positive and negative** values

In [4]:
randNegVal = np.random.randn(10)
print(randNegVal)

[ 0.09881045  1.55877506 -1.24084437 -0.65507101  0.71998075 -1.13496751
 -0.04416657 -0.45995499 -0.69340217  0.30734543]


In [5]:
randNegVal2D = np.random.randn(5,5)
print(randNegVal2D)

[[ 0.41462785 -0.05037975 -0.45524573 -1.04743947  0.32177544]
 [-2.21298458  1.5259088  -0.32916919 -2.09441186  0.44102864]
 [ 0.06216012 -0.87806479  0.1596158   0.84503515  0.19768598]
 [ 0.95280012  0.48209198  1.28293328  0.12466857 -0.67472425]
 [-0.45071763  0.33478066 -0.10105908  0.46048851  0.01235307]]


## `ranf()` function
The `numpy.random.ranf()` function is used to generate an array of a specified shape and fill it with random floating point numbers in the half open interval [0.0,1.0) (0.0 is included in the range and 1.0 is excluded)

In [6]:
randFloatArr = np.random.ranf(5)
print(randFloatArr)

[0.94875097 0.93135781 0.48476875 0.87978091 0.41733042]


In [7]:
randFloatArr1 = np.random.ranf((5,3,2))
print(randFloatArr1)

[[[0.70591444 0.38847281]
  [0.01476751 0.28044897]
  [0.6309181  0.62491293]]

 [[0.47093666 0.50387193]
  [0.97941134 0.60124424]
  [0.46343702 0.45952223]]

 [[0.62885068 0.81307137]
  [0.38760451 0.30686242]
  [0.75501591 0.54120487]]

 [[0.68329582 0.10887547]
  [0.92105952 0.93313326]
  [0.89434174 0.00811621]]

 [[0.71227719 0.54869195]
  [0.93063431 0.00826379]
  [0.63104509 0.48587673]]]


## `randint()` function
The `numpy.random.randint()` function generates a random number within a specified range

In [8]:
randnums = np.random.randint(5,20,10)
print(randnums)

[ 7 15 16 14 19  7 11 18  5 12]


In [9]:
randnums_2D = np.random.randint(5,20,(3,5))
print(randnums_2D)

[[ 9 12  7 12  6]
 [11 17  5 12  7]
 [19 13  9  5 16]]


# Identitity matirix in numpy
`np.identity(n)` returns an identity matrix of order `n`

In [10]:
I = np.identity(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Creating an array with a given shape which is filled with a specified `fill_value`

In [11]:
arr1 = np.full((5,4),10)
print(arr1)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


# Selecting a random value from an array of values
To pick a random value from an array of values we use `numpy.random.choice()` method

It can also return an array of random values with a specified shape

The syntax of `np.random.choice()` method is as follows:-
`np.random.choice(arr,size:int or tuple_of_ints,replace:boolean optional,p:1D array_like:optional)`

```python
import numpy as np
arr = np.array([65,89,98,12,54,65,78,89,156,987,453])
randArrVal = random.choice(arr)
print(randArrVal)
```

In [21]:
arr = np.array([65,89,98,12,54,65,78,89,156,987,453])
randArrVal = np.random.choice(arr,size=(10,5))
print(randArrVal)

[[ 65  89  78  65  65]
 [ 54  89  89 156  12]
 [ 54  65  65  65  54]
 [ 65  98  65  12  98]
 [156  98  65 987  78]
 [ 89  89 453  12  12]
 [ 89  89  65 453  98]
 [ 12  98  54  98 156]
 [ 65  78 453  78  78]
 [ 78 156  65  12  65]]


In [23]:
arr = np.array([65,89,98,12,54,65,78,89,156,987,453])
randArrVal1 = np.random.choice(arr,size=10)
print(randArrVal1)

[ 98  89  89  78  89 156  98  98  12  12]
