# Random Module in numpy

## `rand()` function
The `numpy.random.rand()` function is used to generate random values between 0 and 1

In [2]:
import numpy as np

In [3]:
values = np.random.rand(4)
print(values)

[0.61334919 0.54119873 0.05452854 0.85263562]


In [4]:
var1 = np.random.rand(5,5,3)
print(var1)

[[[0.56585231 0.77941077 0.55996582]
  [0.70431321 0.60709088 0.70926481]
  [0.23088188 0.39046899 0.02249446]
  [0.33523637 0.7367398  0.01002409]
  [0.1078474  0.53906195 0.27528479]]

 [[0.8674732  0.74649011 0.29197869]
  [0.54835199 0.45630005 0.83761797]
  [0.96184086 0.83362944 0.80550113]
  [0.29856075 0.02263449 0.46015428]
  [0.40838802 0.01127111 0.55934356]]

 [[0.84722586 0.36313234 0.66136012]
  [0.22737014 0.16673751 0.64178682]
  [0.21768457 0.00217492 0.49492775]
  [0.20001457 0.08190075 0.24947079]
  [0.74826624 0.3604877  0.363646  ]]

 [[0.81592371 0.30224222 0.10605218]
  [0.77952346 0.19179567 0.54167029]
  [0.86507044 0.08540041 0.11973283]
  [0.42168556 0.35108982 0.54660181]
  [0.43699775 0.18216343 0.50183334]]

 [[0.58036031 0.22710368 0.12665376]
  [0.03589404 0.02047212 0.20656839]
  [0.55062792 0.68168993 0.17829464]
  [0.30659176 0.74352094 0.75592468]
  [0.31782388 0.2338076  0.43388289]]]


## `randn()` function
The `numpy.random.randn()` function is used to generate random values **close to zero** and it may include **positive and negative** values

In [5]:
randNegVal = np.random.randn(10)
print(randNegVal)

[ 1.72871261 -1.45326818 -0.94390243 -0.1537542  -2.09449145  0.14853511
 -0.44073122  0.05317173  0.22548444 -0.54385326]


In [6]:
randNegVal2D = np.random.randn(5,5)
print(randNegVal2D)

[[-1.16003058 -0.80067109 -0.8967638  -0.05058306 -0.10350184]
 [-0.44224909 -0.22853866 -0.66224952  0.89205647 -0.06537568]
 [ 1.87954404 -0.12787924  0.00208493 -0.44660665  1.61856116]
 [-0.59721612  1.01901635 -0.6950311  -0.70204148  1.67126314]
 [ 1.30728847  0.01763928 -0.16717217 -0.57257811 -0.38662455]]


## `ranf()` function
The `numpy.random.ranf()` function is used to generate an array of a specified shape and fill it with random floating point numbers in the half open interval [0.0,1.0) (0.0 is included in the range and 1.0 is excluded)

In [7]:
randFloatArr = np.random.ranf(5)
print(randFloatArr)

[0.80817156 0.30713385 0.20015213 0.19041485 0.88720032]


In [8]:
randFloatArr1 = np.random.ranf((5,3,2))
print(randFloatArr1)

[[[0.56647018 0.66005996]
  [0.79196013 0.59857837]
  [0.97923912 0.00809999]]

 [[0.12970739 0.26737731]
  [0.25282992 0.61810437]
  [0.54150706 0.60848434]]

 [[0.96735202 0.62012333]
  [0.65211891 0.0255916 ]
  [0.94263363 0.97188615]]

 [[0.94654368 0.78906562]
  [0.08282003 0.6327012 ]
  [0.89419618 0.29649379]]

 [[0.59072557 0.01948542]
  [0.12336394 0.19420743]
  [0.52076757 0.76160332]]]


## `randint()` function
The `numpy.random.randint()` function generates a random number within a specified range

In [19]:
randnums = np.random.randint(5,20,10)
print(randnums)

[17 14  7 16 17 16  7 11 16  6]


In [10]:
randnums_2D = np.random.randint(5,20,(3,5))
print(randnums_2D)

[[15  9 16  9 13]
 [ 7 18  8  7 16]
 [ 9 13 10 10  7]]


# Identitity matirix in numpy
`np.identity(n)` returns an identity matrix of order `n`

In [11]:
I = np.identity(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Creating an array with a given shape which is filled with a specified `fill_value`

In [12]:
arr1 = np.full((5,4),10)
print(arr1)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


# Selecting a random value from an array of values
To pick a random value from an array of values we use `numpy.random.choice()` method

It can also return an array of random values with a specified shape

The syntax of `np.random.choice()` method is as follows:-
`np.random.choice(arr,size:int or tuple_of_ints,replace:boolean optional,p:1D array_like:optional)`

```python
import numpy as np
arr = np.array([65,89,98,12,54,65,78,89,156,987,453])
randArrVal = random.choice(arr)
print(randArrVal)
```

In [13]:
arr = np.array([65,89,98,12,54,65,78,89,156,987,453])
randArrVal = np.random.choice(arr,size=(10,5))
print(randArrVal)

[[156  65  89  78 453]
 [ 65  89 156  12  98]
 [156  65  89  98  65]
 [987  65  65  65  89]
 [453  65  98 156  54]
 [ 12 156  65  89  89]
 [ 89  78  89 453  98]
 [156  12  65 453  98]
 [ 12  54 453  98  98]
 [ 89  78  89  54 453]]


In [14]:
arr = np.array([65,89,98,12,54,65,78,89,156,987,453])
randArrVal1 = np.random.choice(arr,size=10)
print(randArrVal1)

[ 65  89 453  54  89  78  65  78 987  89]
