In [15]:
import numpy as np

In [18]:
arr = np.array([[34,87,12,35,98,90,65,67,88,100],
                [45,76,90,88,12,765,12,900,765,123],
                [43,190,187,165,154,154,176,176,198,143],
                [43,98,12,45,98,90,12,34,56,76]])

mat1 = np.asmatrix(arr)
print(mat1)
print(type(mat1))
mat1

[[ 34  87  12  35  98  90  65  67  88 100]
 [ 45  76  90  88  12 765  12 900 765 123]
 [ 43 190 187 165 154 154 176 176 198 143]
 [ 43  98  12  45  98  90  12  34  56  76]]
<class 'numpy.matrix'>


matrix([[ 34,  87,  12,  35,  98,  90,  65,  67,  88, 100],
        [ 45,  76,  90,  88,  12, 765,  12, 900, 765, 123],
        [ 43, 190, 187, 165, 154, 154, 176, 176, 198, 143],
        [ 43,  98,  12,  45,  98,  90,  12,  34,  56,  76]])

In [19]:
val = mat1[3,5]
print(val)

90


In [26]:
for i in range(4):
    for j in range(10):
        print(mat1[i,j])
    print()


34
87
12
35
98
90
65
67
88
100

45
76
90
88
12
765
12
900
765
123

43
190
187
165
154
154
176
176
198
143

43
98
12
45
98
90
12
34
56
76

