# Creating arrays in which all elements are filled with zeros

In [1]:
import numpy as np

In [2]:
arr_zeros = np.zeros(4)
print(arr_zeros)

[0. 0. 0. 0.]


In [3]:
arr1_zeros = np.zeros((3,4))

In [4]:
print(arr1_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Creating an array with all elements filled with ones

In [5]:
arr_ones = np.ones(10)
print(arr_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
arr1_ones =np.ones((3,5))
print(arr1_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Creating an empty array in numpy

In [7]:
arr_empty = np.empty((3,5))
print(arr_empty)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Creating an array with a range of elements

In [16]:
arr_rangeVal = np.arange(1,101)
print(arr_rangeVal)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


# Creating an array with diagonal elements filled with ones

In [36]:
arr_Identity = np.eye(4)
print(arr_Identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [56]:
arr_Identity = np.eye(4)
print(arr_Identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Creating an array with evenly spaced values in a closed interval `[start,stop]`

`np.linspace()` function is used for this purpose

In [84]:
arr_linear = np.linspace(0,20,num=5)
print(arr_linear)

[ 0.  5. 10. 15. 20.]
