# Creating arrays in which all elements are filled with zeros

In [1]:
import numpy as np

In [13]:
arr_zeros = np.zeros(4)
print(arr_zeros)

[0. 0. 0. 0.]


In [14]:
arr1_zeros = np.zeros((3,4))

In [15]:
print(arr1_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Creating an array with all elements filled with ones

In [17]:
arr_ones = np.ones(10)
print(arr_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [37]:
arr1_ones =np.ones((3,5))
print(arr1_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Creating an empty array in numpy

In [29]:
arr_empty = np.empty((3,5))
print(arr_empty)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
